### ISSUE TITLE
epsilon plot should have title

### ISSUE THREAD

**Issue by nielsenmb** [grd349/PBjam#119]
Our Chaos Engineer was very confused about the epsilon plot. 

Adding titles and labels might help.

**Comment by ojhall94** [comment]
Seconded, I too was confused :)

**Comment by grd349** [comment]
For whatever reason, plt.fill_between does not seems to be able to handle the label I give it - it just doesn't appear.  Will need to do this the old fashioned way.

**Comment by grd349** [comment]
Ignore me - we were missing a legend function and there was a legend because lightkurve was providing it.  I have fixed this now.  I went for the slightly cryptic but possibly accurate r'$\propto P(\ell = 0)$'.

<img width="1029" alt="Screenshot 2019-07-20 at 13 28 06" src="https://user-images.githubusercontent.com/14784265/61578645-43559300-aaf2-11e9-8dda-edf619b6fe46.png">

**Comment by nielsenmb** [comment]
Should it not be \proptoP(\nu_{l=0})?

**Comment by grd349** [comment]
Yes - it should be with the nu ... I'll fix.
