### ISSUE TITLE
PBjam can't find HD numbers in lightkurve cache

### ISSUE THREAD

**Issue by nielsenmb** [grd349/PBjam#122]
At the moment PBjam can't find HD numbers in the cache. The reason being that it first strips the KIC/EPIC/TIC from the ID and then does a wildcard search in the carche directory. 

The files are stored in the format relevant to the kepler, tess, k2 missions, e.g.,  tess2018263035959-s0003-0000000122555698-0123-s_lc.fits, HD lookups obviously wont work. 

A potential solution to this would be to first try to use lightkurve.search_lightcurvefile with the provided ID, and if it returns anything use that to lookup the files in the cache. If in offline-mode it will then fall back to looking up the numbers with a wildcard search as it does now.

Otherwise, maybe there are some smart Lightkurve people who can think of a solution.

**Comment by ojhall94** [comment]
I will try and be the smart lightkurve person and fix this after lunch :)

**Comment by ojhall94** [comment]
I'm a little lost in the code around this. It's failing in `jar.py`, right? All the x_to_y() functions are pretty confusing to me.

So if I understand correctly:
- Starting a session will automatically check the cache for each ID.
- If nothing is found in the cache, it will check MAST and download the data through lightkurve.

I'm confused about what the error is--- is it that HD numbers will always result in it downloading from MAST? Or does query_mast() not work?

**Comment by ojhall94** [comment]
Had a chat with Martin:

It should be able to:
- Check if the star you want is in cache
- If this check fails (for example, if we have a HD number), search a lightkurvefile
- If is fails due to no connection to the internet, tell the user to put in the lightcurve themselves.
- Check the cache using the KIC or TIC identifier from search_lightkurvefile
- If this doesn't work, tell the user to put in the data themselves.

**Comment by nielsenmb** [comment]
This can probably in part be solved by also completing Issue #55

**Comment by nielsenmb** [comment]
Fixed in PR #246
