### ISSUE TITLE
Asymptotic_fit plot does not work correctly when running in session

### ISSUE THREAD

**Issue by alexlyttle** [grd349/PBjam#167]
As discussed in person with @nielsenmb, the asymptotic_fit plot does not work correctly when running in `session` but does work in `star`. It doesn't appear to be using the full sample set, leaving incomplete contour plots. The image below is what is produced when running the session example in the docs:

![image](https://user-images.githubusercontent.com/43786145/66055871-2267e000-e52e-11e9-87cf-82993deadc39.png)

I traced the fault back to [a few lines of code](https://github.com/grd349/PBjam/blob/f830766db0ab0befcaa27610f769bd68bbba5f5a/pbjam/asy_peakbag.py#L542) in `asy_peakbag.py` (lines 542-548):

```python
if self.store_chains:
    self.samples = self.fit.flatchain
    self.lnlike_fin = self.fit.flatlnlike
else:
    self.samples = self.fit.chain[:,-1,:]
    self.lnlike_fin = np.array([self.fit.likelihood(self.fit.chain[i,-1,:]) for i in range(self.fit.nwalkers)])
    self.lnprior_fin = np.array([self.fit.lp(self.fit.chain[i,-1,:]) for i in range(self.fit.nwalkers)])
```

The key difference between `star` and `session` is that `star` sets `store_chains=True` by default when called, whereas `session` overwrites this by passing `store_chains=False` when calling `star`. Therefore, `session` sets `self.samples` to only the last slice of the chain, giving the observed contour plot.

This could be fixed by rewriting the above code to not depend on `store_chains` in this way?

**Comment by grd349** [comment]
Excellent work @alexlyttle  - this looks like an initial value problem to me - is the way the code is run in session and star identical (wrt inputs at least)?

**Comment by alexlyttle** [comment]
The code is run identically wrt to inputs in star and session, except for `store_chains` (`True` in star and `False` in session by default). This is how I traced it to the lines of code quoted above. Chatted to @nielsenmb a moment ago and he agrees that this is what caused the issue, but he may be able to explain why more easily!

The main issue is that if you pass `store_chains=False`, when calling either star or session, it breaks the asymptotic_fit plot because of the if-statement quoted above. I believe Martin intends to rewrite the above lines which should hopefully, in-turn, fix this Issue.

**Comment by nielsenmb** [comment]
It's simply due to the fact that if store_chains=True in one case and not
in the other.

In asy_peakbag if store_chains=False, then only the last step in the chains
is saved, and sent to asy_fit.samples, which plotting.plot_corner uses.

The fit is still perfectly fine, since the summary statistics that are
passed to asy_fit.modeID are computed before this. It's just the corner
plot that is affected.

I think I'll remove the store_chains check in asy_peakbag, and move it out
to the star.run_asy_peakbag and let it refer to just dumping to disk or
not. The issue of it consuming memory or not can/should be investigated,
and perhaps someone who knows more about memory handling will come along
some day and help us. For a single star it won't be an issue, but for a
session of several stars it probably will. For now though we can just
advise only doing sessions of a few stars at a time.

**Comment by nielsenmb** [comment]
Fixed in latest PR
