### ISSUE TITLE
Session struggling with challenging red clump star, kde fails?

### ISSUE THREAD

**Issue by alexlyttle** [grd349/PBjam#169]
Calling an instance of `session` on KIC8527188, an evolved red clump star, produces some problems that seem to be to do with the kde. When I manually download, producing a periodogram via Lightkurve and then use the `star` class, the fit is improved. I'm not too sure what is going on here, but two major differences are with the following plots:

**Via session**
![kde_KIC8527188](https://user-images.githubusercontent.com/43786145/66204457-c96d8880-e6a2-11e9-84c0-4841eec23d55.png)
![peakbag_KIC8527188](https://user-images.githubusercontent.com/43786145/66207236-291b6200-e6aa-11e9-866e-4cf05de329d3.png)

**Via star**
![kde_KIC8527188](https://user-images.githubusercontent.com/43786145/66204468-d0949680-e6a2-11e9-8711-456e5201b94b.png)
![peakbag_KIC8527188](https://user-images.githubusercontent.com/43786145/66207212-199c1900-e6aa-11e9-96ab-fd04846937e6.png)

There also appears to be very heavy smoothing in the second-to-last image.

To see the full Jupyter notebook with the code for running this star via `session` and `star`, I was able to attach a pdf of the output:
[KIC8527188.pdf](https://github.com/grd349/PBjam/files/3690301/KIC8527188.pdf)

**Comment by nielsenmb** [comment]
I think this may in part be due to session using the entire spectrum,
0-Nyquist, where your star example uses a section of the spectrum around
numax. That's the only difference I can see.

Ultimately this shouldn't have much of an effect though, since the
information about the modes in the spectrum is identical in both cases.

Try running the star example without limiting the frequency range, and see
if you get same/similar results.

Why the kde stage spectrum plots are so different though I'm not sure, the
y scale should at least be similar.

W.r.t the smoothing, the amount of smoothing is fixed to 0.1/df. It usually
looks nicer to scale the smoothing by dnu, but since the plot function may
not always know what dnu is (depending on what stage is being plot), I
chose to just fix it to 0.1/df.

Nice write-up though, it's good to have a well-studied 'bad' case as well
as the default 'good' star that we keep using in the example files.

**Comment by grd349** [comment]
Where are we on this?  Does session restrict the range of the power spectrum now?

**Comment by grd349** [comment]
@nielsenmb @alexlyttle  Bump - is this fixed now?

**Comment by nielsenmb** [comment]
Don't know if it's fixed, but it might be obsolete, since the code has changed. 

I'd say run the tgt again and see if it works.

**Comment by alexlyttle** [comment]
I can run the code for the original issue again with updated PBjam and see if that works. Should I use CPNest?

**Comment by nielsenmb** [comment]
Either should be good.

**Comment by alexlyttle** [comment]
It seems to work now, using CPNest here. Will try with emcee too. The prior seems to be improved down here too, even though it's a bit off from the l=0s the sampler still seems to find a sensible solution. It did have to expand the prior from ~50 stars so could explain it.

![image](https://user-images.githubusercontent.com/43786145/86341594-69fed200-bc4e-11ea-9619-e736a9ff50e9.png)

![image](https://user-images.githubusercontent.com/43786145/86342030-f5786300-bc4e-11ea-81c9-36118adec9fc.png)

![image](https://user-images.githubusercontent.com/43786145/86342338-5b64ea80-bc4f-11ea-910d-ed90892d6e60.png)

![image](https://user-images.githubusercontent.com/43786145/86342311-52741900-bc4f-11ea-913d-2831b18a99dc.png)

**Comment by nielsenmb** [comment]
Closing this.
